version: '2'
services:
    nginx:
        build: nginx/
        ports:
            - "1443:1443"
        volumes:
            - ./nginx/certificates/:/certificates
            - ./nginx/letsencrypt-webroot:/letsencrypt
        depends_on:
            - web
    web:
        build: webapp/
        volumes:
            - ./webapp/instance/:/code/instance
            - ./webapp/weight:/code/weight
            - ./data/:/data
